# Generated by Django 3.0.6 on 2020-05-18 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagsh',
            options={'ordering': ('name',), 'verbose_name': 'Багш', 'verbose_name_plural': 'Багш Нарын Жагсаалт'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Сэтгэгдэл', 'verbose_name_plural': 'Сэтгэгдэлийн Жагсаалт'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created',), 'verbose_name': 'Бидэнтэй Холбогдох', 'verbose_name_plural': 'Бидэнтэй Холбогдох Жагсаалт'},
        ),
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ('-created',), 'verbose_name': 'Хууль', 'verbose_name_plural': 'Хуулийн Жагсаалт'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'Мэдээ', 'verbose_name_plural': 'Мэдээний Жагсаалт'},
        ),
        migrations.RemoveField(
            model_name='law',
            name='body',
        ),
        migrations.AddField(
            model_name='law',
            name='pdf',
            field=models.FileField(default=None, upload_to='laws', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Хуулийн PDF Агуулга'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Агуулга'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Эмайл Хаяг'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Хэрэглэгчийн Нэр'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWeb.News', verbose_name='Холбогдох Мэдээ'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Эмайл Хаяг'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='fullName',
            field=models.CharField(max_length=254, verbose_name='Бүтэн Нэр'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(verbose_name='Агуулга'),
        ),
        migrations.AlterField(
            model_name='law',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWeb.Bagsh', verbose_name='Зохиогч'),
        ),
        migrations.AlterField(
            model_name='law',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Сайтын Зам'),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWeb.Bagsh', verbose_name='Зохиогч'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='Агуулга'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Сайтын Зам'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Гарчиг'),
        ),
    ]
