# Generated by Django 3.0.6 on 2020-05-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0003_news_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
