# Generated by Django 3.0.6 on 2020-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0004_auto_20200518_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
