# Generated by Django 3.0.6 on 2020-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0005_auto_20200518_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Мэдээний Төрлийн Нэр')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мэдээний Төрөл',
                'verbose_name_plural': 'Мэдээний Төрлийн Жагсаалт',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False, null=True, verbose_name='Онцлог Эсэх?'),
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='MainWeb.NewsCategory', verbose_name='Мэдээний Төрлийн Жагсаалт'),
        ),
    ]
