# Generated by Django 3.0.6 on 2020-05-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0007_auto_20200518_1848'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bagsh',
            table='Сайтын_Хэсгүүд',
        ),
    ]
