# Generated by Django 3.0.6 on 2020-05-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0008_auto_20200521_0642'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bagsh',
            table=None,
        ),
    ]
