# Generated by Django 3.0.6 on 2020-05-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0010_contactusglobal_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsGlobal',
            new_name='Settings',
        ),
    ]
