# Generated by Django 3.0.6 on 2020-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0012_settings_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='hamtragchBaiguulga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(blank=True, default='', max_length=250)),
                ('img', models.ImageField(default='', upload_to='bidniTuhai')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='alsinHaraa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='bidniDesc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='bidniImg',
            field=models.ImageField(default='', upload_to='bidniTuhai'),
        ),
        migrations.AddField(
            model_name='settings',
            name='bidniMiniDesc',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='settings',
            name='bidniTitle',
            field=models.CharField(blank=True, default='Бидний Тухай', max_length=250),
        ),
        migrations.AddField(
            model_name='settings',
            name='erhemZorilgo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='mendchilgee',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='hamtragchBaiguulgaZurga',
            field=models.ManyToManyField(to='MainWeb.hamtragchBaiguulga'),
        ),
    ]
