# Generated by Django 3.0.6 on 2020-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0013_auto_20200521_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagsh',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='bagsh',
            name='fb',
            field=models.URLField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bagsh',
            name='roleDesc',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bagsh',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Цахим Хаяг'),
        ),
    ]
